### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'unknown'

### ISSUE THREAD

**Issue by woopstar** [syssi/homeassistant-goecharger-mqtt#102]
After update to latest version of HA and go-e, I'm starting to see this error in the logs:

```yaml
2023-05-06 16:15:08.957 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'unknown'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 852, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.go_echarger_222819_dwo has device class energy, state class None unit Wh and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown ()
```

**Comment by arboeh** [comment]
Same here, see also https://github.com/home-assistant/core/issues/92588
Problem exists for other intergations also since update to 2023.5

**Comment by syssi** [comment]
I will take care later the week!

**Comment by woopstar** [comment]
Any updates on this one @syssi ?

**Comment by syssi** [comment]
Thanks for your patience! I've pushed a fix and will prepare a new release today.
