### ISSUE TITLE
KeyError: 'Wh': Wh is not a recognized volume unit.

### ISSUE THREAD

**Issue by woopstar** [syssi/homeassistant-goecharger-mqtt#106]
```
2023-06-08 14:34:45.561 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for sensor.go_echarger_222819_wh
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 72, in convert
    from_ratio = cls._UNIT_CONVERSION[from_unit]
KeyError: 'Wh'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 287, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 607, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/energy/sensor.py", line 419, in async_state_changed_listener
    self._update_cost()
  File "/usr/src/homeassistant/homeassistant/components/energy/sensor.py", line 385, in _update_cost
    converted_energy_price = converter(
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 74, in convert
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Wh is not a recognized volume unit.
```

**Comment by woopstar** [comment]
This came because I added the Charged Energy as a Gas Sensor in the energy dashboard.
