### ISSUE TITLE
sensor.go_echarger_clp bug

### ISSUE THREAD

**Issue by kalaws** [syssi/homeassistant-goecharger-mqtt#110]
HA is throwing the following error. I suppose the properties of `sensor.go_echarger_clp` are perhaps incorrect?

```
2023-09-01 12:06:30.911 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 591, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '[6,8,10,13,16]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 880, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 717, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 595, in state
    raise ValueError(
ValueError: Sensor sensor.go_echarger_clp has device class 'current', state class 'measurement' unit 'A' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '[6,8,10,13,16]' (<class 'str'>)
```

**Comment by MarkusMit** [comment]
I have the same issue with `clp`, and a similar with `ocu`:

> Logger: homeassistant
Source: components/sensor/__init__.py:671
First occurred: 17:20:09 (18 occurrences)
Last logged: 17:28:39

> Error doing job: Task exception was never retrieved

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '[6,8,10,12,16]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 667, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: '[6,8,10,12,16]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 919, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 671, in state
    raise ValueError(
ValueError: Sensor sensor.go_echarger_200xxx_clp has device class 'current', state class 'measurement' unit 'A' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '[6,8,10,12,16]' (<class 'str'>)
```

Home Assistant
- Core 2024.2.1
- Supervisor 2024.01.1
- Operating System 11.5
- Frontend 20240207.1
- _go-eCharger integration for Home Assistant using the MQTT API_ 0.22.0

**Comment by showupch** [comment]
I got this issue also.

**Comment by syssi** [comment]
Fixed by #155

**Comment by syssi** [comment]
You update the integration to version 0.24.1.

**Comment by showupch** [comment]
> You update the integration to version 0.24.1.

Hi syssi. mys system still on 0.24.0 there is a special way to update to 0.24.1 or it comes automatic?
