### ISSUE TITLE
Entities missing with home assistant 2023.11

### ISSUE THREAD

**Issue by Duetting** [syssi/homeassistant-goecharger-mqtt#121]
After updating home assistant to 2023.11 yesterday quite a few entities went missing.
Here an example message from the logs:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:367
Integration: Sensor (documentation, issues)
First occurred: 07:43:10 (1 occurrences)
Last logged: 07:43:10

Error while setting up goecharger_mqtt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.go_echarger_056402_result cannot be added as the entity category is set to config

**Comment by syssi** [comment]
I will prepare a fix. The value `config` isn't allowed as `entity_category` anymore.

**Comment by landandseatechnology** [comment]
Hi syssi,
Looking forward to the release of your fix. I am also missing 18 different entities since  I updated to Home Assistance 2023.11
The main entity I miss is the **frc** sensor, to use the force state feature of the go_e charger.

Best Regards

**Comment by syssi** [comment]
I've pushed a fix and prepared a bugfix release. Please give it a try!

**Comment by mf76130** [comment]
Awesome, thanks a lot. Working for me
