### ISSUE TITLE
Setup failing due to AssertionError

### ISSUE THREAD

**Issue by alangibson-philips** [syssi/homeassistant-goecharger-mqtt#55]
Thanks for the integration. I’m unfortunately not getting any data out of the box. I'm seeing this in the logs:

```
Logger: homeassistant
Source: components/mqtt/client.py:214
First occurred: 3:23:25 PM (3 occurrences)
Last logged: 3:29:27 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 151, in async_wrapper
    await async_func(*args)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/discovery.py", line 282, in async_integration_message_received
    result = await hass.config_entries.flow.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/goecharger_mqtt/config_flow.py", line 79, in async_step_mqtt
    assert subscribed_topic == "/go-eCharger/+/var"
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 153, in async_wrapper
    log_exception(format_err, *args)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 115, in log_exception
    friendly_msg = format_err(*args)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 214, in <lambda>
    f"Exception in {msg_callback.__name__} when handling msg on "
AttributeError: 'functools.partial' object has no attribute '__name__'
```

This assert seems to be blowing up async_step_mqtt

```
assert subscribed_topic == "/go-eCharger/+/var"
```

At the very least, the config process should probably be aborted with self.async_abort there so that there is feedback to the user.

Also, that assert is a bit odd given that there are two topic names listed in the manifest.json

```
  "mqtt": [
    "/go-eCharger/+/var",
    "go-eCharger/+/var"
  ],
```

I did get it working with this quick hack:

1. Comment out

```
assert subscribed_topic == "/go-eCharger/+/var"
```
2. Change base topic from /go-eCharger to go-eCharger during setup

**Comment by syssi** [comment]
Thank you for your very detailed bug report! I've prepared a fix which will be merged in a few seconds.

**Comment by magenbrot** [comment]
Hi! I'm on 0.14.1 with the above fix, but I still get this assertion error in the logs during startup:
```
2022-11-12 10:14:20.007 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 154, in async_wrapper
    await async_func(*args)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/discovery.py", line 292, in async_integration_message_received
    result = await hass.config_entries.flow.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/goecharger_mqtt/config_flow.py", line 79, in async_step_mqtt
    assert subscribed_topic == ["/go-eCharger/+/var", "go-eCharger/+/var"]
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 156, in async_wrapper
    log_exception(format_err, *args)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 115, in log_exception
    friendly_msg = format_err(*args)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 225, in <lambda>
    f"Exception in {msg_callback.__name__} when handling msg on "
AttributeError: 'functools.partial' object has no attribute '__name__'
```
Please let me know if you need additional info.

**Comment by syssi** [comment]
My fault. I will push a fix in a minute.

**Comment by syssi** [comment]
Please give it another try using version `0.14.2`.

**Comment by magenbrot** [comment]
@syssi it's working. Thank you for the quick fix and the integration itself :smile:
